// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDuGAa3PVIaiVbp8Vr9Hc69xAt3DXvX8',
    appId: '1:732489406915:web:9b950999faf00f07960576',
    messagingSenderId: '732489406915',
    projectId: 'obsidian-ai-c8836',
    authDomain: 'obsidian-ai-c8836.firebaseapp.com',
    storageBucket: 'obsidian-ai-c8836.firebasestorage.app',
    measurementId: 'G-5HDPQLN8XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EZklOomv11ddk_DriEDvF7GmQKnkX7k',
    appId: '1:732489406915:android:4f574ccf3fc29acc960576',
    messagingSenderId: '732489406915',
    projectId: 'obsidian-ai-c8836',
    storageBucket: 'obsidian-ai-c8836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhUignof75yfvtD-1UtBv9-yG8-9pKHVU',
    appId: '1:732489406915:ios:dfa619fe99f9f043960576',
    messagingSenderId: '732489406915',
    projectId: 'obsidian-ai-c8836',
    storageBucket: 'obsidian-ai-c8836.firebasestorage.app',
    androidClientId: '732489406915-nabker8d5lcjs793o7jq5k47jmuu3p07.apps.googleusercontent.com',
    iosClientId: '732489406915-bcmh06poijnlje2jb1hpjd3vdd9f818d.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiProductivityAssistant',
  );
}
